### ISSUE TITLE
add components without logic

### ISSUE THREAD

**Issue by topgggggg** [Team-GAKN/pms_employee_management_frontend#1]
## Description
We have to add the UI components for the frontend, so we are able see things. These will be implemented without logic. These should use Bootstrap 5 as well.

## Todo
  - [x] bootstrap 5 is added
  - [x] button is created
  - [x] input is created
  - [x] navbar is created
  - [x] qualification label is created
  - [x] employee card is created

## For Developer
Look at the [wireframe](https://www.figma.com/file/kuRENyIMK2fM99C0vYnU5h/Wireframe-Designer-(Community)) for reference.
