### ISSUE TITLE
Project cleanup

### ISSUE THREAD

**Issue by topgggggg** [Team-GAKN/pms_employee_management_frontend#22]
## Description
After we have completed our issues, we have to cleanup remaining stuff.

## Todo
  - [ ] refreshing after editing employees is fixed
  - [ ] project is reformatted correctly
  - [ ] small mistakes are fixed
